apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver-test3
  template:
    metadata:
      labels:
        app: echoserver-test3
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.8
          name: echoserver
          ports:
            - containerPort: 8080
